server:
  port: 10001
spring:
  application:
    name: springcloud-module1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
  instance:
    prefer-ip-address: true #